import Link from "next/link";
import FinanceShell, { selectedMonth, SetupMessage } from "../FinanceShell";
import { BillForm, PaymentForm } from "../FinanceForms";
import { loadFinance } from "../../../lib/financeData";
import { BILL_CATEGORIES, summarizeBills } from "../../../lib/finance";
import { dateKey, money, monthLabel } from "../../../lib/accounting";
import styles from "../accounts.module.css";

export const dynamic = "force-dynamic";
export default async function PurchasesPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const params = await searchParams, month = selectedMonth(params.month), today = dateKey(new Date()), data = await loadFinance(month);
  const summary = data.ready ? summarizeBills(data.bills, data.payments, month) : null;
  const selected = data.ready ? data.bills.find(b => b.id === params.edit) : undefined;
  const view = params.view === "unpaid" ? "unpaid" : "month";
  const rows = data.ready ? data.bills.filter(b => !b.voided && (view === "unpaid" ? b.total_paise > (summary!.paidByBill.get(b.id) || 0) : b.invoice_date.startsWith(month))).sort((a, b) => b.invoice_date.localeCompare(a.invoice_date) || b.id.localeCompare(a.id)) : [];
  const pageCount = Math.max(1, Math.ceil(rows.length / 30)), page = Math.min(pageCount, Math.max(1, parseInt(params.page || "1") || 1));
  return <FinanceShell active="purchases" month={month} title="Purchases & expenses" description="Supplier invoices, payment history and input GST in one place.">
    {!data.ready && <SetupMessage message={data.message} />}
    <div className={styles.metrics}>{[["Bills this month", summary?.purchases, monthLabel(month)], ["Payments this month", summary?.cashPaid, "By actual payment date"], ["Supplier balance due", summary?.outstanding, "Across all recorded bills"], ["Verified input GST", summary?.eligibleItc, "Accounts-reviewed credit · not a filed claim"]].map(([label, value, note]) => <section key={String(label)} className={styles.metric}><h2>{label}</h2><strong>{typeof value === "number" ? money(value) : "—"}</strong><p>{note}</p></section>)}</div>
    <section className={styles.panel} id="bill-form"><details open={!!selected}><summary className={styles.formSummary}>{selected ? `Edit ${selected.invoice_number} · ${selected.supplier}` : "+ Add supplier bill or expense"}</summary><BillForm key={selected ? `${selected.id}:${selected.version}` : "new"} bill={selected} today={today} enabled={data.ready} /></details>{selected && <Link href={`/accounts/purchases?month=${month}#bill-form`} className={styles.footnote}>Add a different bill</Link>}</section>
    {selected && data.ready && <section className={styles.panel}><h2>Payments · {selected.invoice_number}</h2><p>Outstanding: <strong>{money(selected.total_paise - (summary!.paidByBill.get(selected.id) || 0))}</strong></p><PaymentForm billId={selected.id} outstanding={selected.total_paise - (summary!.paidByBill.get(selected.id) || 0)} today={today} /><ul className={styles.paymentHistory}>{data.payments.filter(p => p.bill_id === selected.id).sort((a, b) => b.paid_on.localeCompare(a.paid_on)).map(p => <li key={p.id}><strong>{money(p.amount_paise)}</strong> · {p.paid_on} · {p.reference}</li>)}</ul></section>}
    <section className={styles.panel}><div className={styles.sectionTitle}><div><p className={styles.eyebrow}>PURCHASE REGISTER</p><h2>{view === "unpaid" ? "All unpaid supplier bills" : monthLabel(month)}</h2></div>{data.ready && <a href={`/api/accounts/finance-export?month=${month}`}>Download monthly register ↓</a>}</div><nav className={styles.tabs} aria-label="Purchase filters"><Link href={`/accounts/purchases?month=${month}`} aria-current={view === "month" ? "page" : undefined}>This month</Link><Link href={`/accounts/purchases?month=${month}&view=unpaid`} aria-current={view === "unpaid" ? "page" : undefined}>All unpaid</Link></nav><div className={styles.tableWrap}><table><thead><tr><th>Invoice / supplier</th><th>Category</th><th>Total</th><th>Paid / due</th><th>Input GST</th><th>Manage</th></tr></thead><tbody>{rows.slice((page - 1) * 30, page * 30).map(b => {
      const paid = summary!.paidByBill.get(b.id) || 0, due = b.total_paise - paid;
      return <tr key={b.id}><td><strong>{b.invoice_number}</strong><small>{b.supplier}</small><small>{b.invoice_date}</small></td><td>{BILL_CATEGORIES[b.category]}<small>Expense month {b.service_month}</small></td><td>{money(b.total_paise)}</td><td>{money(paid)} paid<small className={due && b.due_date && b.due_date < today ? styles.reviewLink : undefined}>{due ? `${money(due)} due${b.due_date ? ` · ${b.due_date}` : ""}` : "Fully paid"}</small></td><td>{b.itc_status === "eligible" ? "Verified eligible" : b.itc_status === "pending" ? "Needs review" : "Not eligible"}<small>{money(b.cgst_paise + b.sgst_paise + b.igst_paise)}</small></td><td><Link href={`/accounts/purchases?month=${month}&edit=${b.id}#bill-form`}>Edit / record payment</Link>{b.document_path && <small><a href={`/api/accounts/bills/${b.id}/invoice`}>Supplier invoice ↓</a></small>}</td></tr>;
    })}{!rows.length && <tr><td colSpan={6} className={styles.empty}>{data.ready ? "No bills in this view. Add a supplier invoice to start tracking purchases." : "Purchase records will appear after setup."}</td></tr>}</tbody></table></div><div className={styles.pagination}><span>{rows.length} bills · Page {page} of {pageCount}</span><div>{page > 1 && <Link href={`/accounts/purchases?month=${month}&view=${view}&page=${page - 1}`}>← Previous</Link>}{page < pageCount && <Link href={`/accounts/purchases?month=${month}&view=${view}&page=${page + 1}`}>Next →</Link>}</div></div><p className={styles.footnote}>Input GST awaiting review: {summary ? money(summary.pendingItc) : "—"}. Confirm eligibility and GSTR-2B reconciliation before marking credit eligible.</p></section>
  </FinanceShell>;
}
