import FinanceShell, { selectedMonth, SetupMessage } from "../FinanceShell";
import { MetaSyncButton } from "../FinanceForms";
import MetaBillingCheck from "../MetaBillingCheck";
import { loadFinance } from "../../../lib/financeData";
import { dateKey, money, monthLabel, weekStart } from "../../../lib/accounting";
import styles from "../accounts.module.css";
export const dynamic = "force-dynamic";
export default async function AdvertisingPage({ searchParams }: { searchParams: Promise<{ month?: string }> }) {
  const month = selectedMonth((await searchParams).month), data = await loadFinance(month), now = new Date(), today = dateKey(now);
  const sync = data.ready ? data.syncs.find(s => s.month === month) : undefined;
  const latest = data.ready ? data.syncs.slice().sort((a, b) => b.synced_at.localeCompare(a.synced_at))[0] : undefined;
  const spend = data.ready ? data.daily.reduce((n, d) => n + d.spend_paise, 0) : 0;
  const campaigns = data.ready ? new Map(data.campaigns.map(c => [c.campaign_id, { ...c, spend: 0, clicks: 0, impressions: 0, purchases: 0 }])) : new Map();
  if (data.ready) for (const row of data.daily) {
    if (!campaigns.has(row.campaign_id)) campaigns.set(row.campaign_id, { account_id: row.account_id, campaign_id: row.campaign_id, name: row.campaign_name, effective_status: "NOT_IN_CURRENT_SNAPSHOT", daily_budget_paise: null, lifetime_budget_paise: null, objective: "", spend: 0, clicks: 0, impressions: 0, purchases: 0 });
    const c = campaigns.get(row.campaign_id)!; c.spend += row.spend_paise; c.clicks += row.clicks; c.impressions += row.impressions; c.purchases += row.purchases;
  }
  const metaBills = data.ready ? data.bills.filter(b => !b.voided && b.category === "meta_ads" && b.service_month === month) : [];
  const billedBase = metaBills.reduce((n, b) => n + b.subtotal_paise, 0);
  const currentSync = data.ready ? data.syncs.find(s => s.month === today.slice(0, 7) && s.through_date >= today) : undefined;
  const week = weekStart(now);
  const previousMonthEnd = new Date(new Date(`${today.slice(0, 7)}-01T00:00:00Z`).getTime() - 86400000).toISOString().slice(0, 10);
  const weekCovered = currentSync && (week.slice(0, 7) === today.slice(0, 7) || (data.ready && data.syncs.some(s => s.month === week.slice(0, 7) && s.through_date >= previousMonthEnd)));
  const recentSpend = (from: string) => data.ready ? data.currentDaily.filter(d => d.day >= from && d.day <= today).reduce((n, d) => n + d.spend_paise, 0) : 0;
  return <FinanceShell active="advertising" month={month} title="Meta advertising" description="Advertising spend and campaign status, alongside your paid-order accounts.">
    {!data.ready && <SetupMessage message={data.message} />}
    <MetaBillingCheck key={month} month={month} configured={!!process.env.META_ADS_ACCESS_TOKEN && /^\d+$/.test((process.env.META_AD_ACCOUNT_ID || "").replace(/^act_/, ""))} />
    <section className={styles.panel}><div className={styles.sectionTitle}><div><p className={styles.eyebrow}>CONNECTION</p><h2>{data.ready && data.metaConfigured ? "Meta account configured" : "Connect your Meta ad account"}</h2></div><MetaSyncButton month={month} enabled={data.ready && data.metaConfigured && month <= today.slice(0, 7)} /></div><p className={styles.footnote}>{data.ready && data.metaConfigured ? `Ad account ${data.accountId}. ${latest ? `Campaign snapshot: ${new Date(latest.synced_at).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST.` : "Run the first sync to load campaigns."}` : "An administrator needs to connect the advertising account with read access. Your WhatsApp connection does not grant advertising access."}</p>{sync && <p className={styles.footnote}>{monthLabel(month)} spend synced through {sync.through_date}. Last fetched {new Date(sync.synced_at).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST. Meta may revise recent results.</p>}</section>
    <div className={styles.metrics}>{[["Spend today", currentSync ? recentSpend(today) : null], ["Spend this week", weekCovered ? recentSpend(week) : null], ["Spend this month", currentSync ? recentSpend(`${today.slice(0, 7)}-01`) : null]].map(([label, value]) => <section key={String(label)} className={styles.metric}><h2>{label}</h2><strong>{typeof value === "number" ? money(value) : "Needs sync"}</strong><p>India time · latest daily reports</p></section>)}</div>
    <div className={styles.metrics}><section className={styles.metric}><h2>Spend · {monthLabel(month)}</h2><strong>{sync ? money(spend) : "Not synced"}</strong><p>Advertising delivery cost · INR</p></section><section className={styles.metric}><h2>Campaigns marked active</h2><strong>{latest ? data.ready ? data.campaigns.filter(c => c.effective_status === "ACTIVE").length : "—" : "—"}</strong><p>From latest snapshot; active does not guarantee delivery</p></section><section className={styles.metric}><h2>Supplier invoices · base</h2><strong>{data.ready ? money(billedBase) : "—"}</strong><p>Meta bills allocated to this month</p></section><section className={styles.metric}><h2>Spend less billed base</h2><strong>{sync ? money(spend - billedBase) : "—"}</strong><p>Reconcile billing periods and adjustments</p></section></div>
    <section className={styles.panel}><div className={styles.sectionTitle}><div><p className={styles.eyebrow}>CAMPAIGN REGISTER</p><h2>Current status & selected-month performance</h2></div></div><div className={styles.tableWrap}><table><thead><tr><th>Campaign</th><th>Latest status</th><th>Budget</th><th>Spend</th><th>Clicks / impressions</th><th>Meta purchases / cost</th></tr></thead><tbody>{Array.from(campaigns.values()).sort((a, b) => b.spend - a.spend).map(c => <tr key={c.campaign_id}><td className={styles.wrapCell}><strong>{c.name}</strong><small>{c.objective}</small></td><td><span className={c.effective_status === "ACTIVE" ? styles.paidBadge : styles.paymentTag}>{c.effective_status.replaceAll("_", " ")}</span></td><td>{c.daily_budget_paise ? `${money(c.daily_budget_paise)} / day` : c.lifetime_budget_paise ? `${money(c.lifetime_budget_paise)} lifetime` : "Ad-set budget / not supplied"}</td><td>{sync ? money(c.spend) : "—"}</td><td>{sync ? `${c.clicks.toLocaleString()} / ${c.impressions.toLocaleString()}` : "—"}</td><td>{sync ? c.purchases.toLocaleString() : "—"}<small>{sync && c.purchases > 0 ? `${money(Math.round(c.spend / c.purchases))} per Meta purchase` : "—"}</small></td></tr>)}{!campaigns.size && <tr><td className={styles.empty} colSpan={6}>{latest ? "No campaigns in the latest account snapshot or selected month." : "Campaigns will appear after the first successful sync."}</td></tr>}</tbody></table></div><p className={styles.footnote}>Meta purchase attribution is a separate metric from verified paid orders. A paused campaign may still have spend earlier in the month. Invoice base amounts reconcile spend and are not added as a second advertising expense.</p></section>
  </FinanceShell>;
}
